[Auth Exchange] Add Duration parser from swift-protobuf
firebase/firebase-ios-sdk pull request #10653
Opened 2023-01-06 22:10 UTC by andrewheard

Added a helper method to deserialize [`google.protobuf.Duration`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Duration) fields from their JSON representation. This method is derived from [`Google_Protobuf_Duration+Extensions.swift`](https://github.com/apple/swift-protobuf/blob/ab3a58b7209a17d781c0d1dbb3e1ff3da306bae8/Sources/SwiftProtobuf/Google_Protobuf_Duration+Extensions.swift) in the [`swift-protobuf`](https://github.com/apple/swift-protobuf) project.

#no-changelog

2023-01-06 22:45 UTC, paulb777 reviewed
The 3P structure looks good.

Please fix other style issues. Should be ok to exclude the sample from check_imports

2023-01-06 22:45 UTC, paulb777 commented on FirebaseAuthExchange/Apps/AuthExchange/Podfile
>    pod 'FirebaseInstallations'
Paths should be added for all Firebase products to test with the versions in the repo instead of released versions.

2023-01-06 22:45 UTC, paulb777 commented on FirebaseAuthExchange/Apps/ObjcSample/Podfile
>    pod 'FirebaseInstallations'
Here also

2023-01-06 23:06 UTC, ncooke3 requested changes
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/firebase/firebase-ios-sdk/10653)



<hr />

In: **FirebaseAuthExchange/Apps/ObjcSample/ObjcSample/main.m**:

```
> Line 1
// Copyright 2022 Google LLC
```
// Copyright 2023 Google LLC


<hr />

👀 @andrewheard, @rosalyntan it's your turn please take a look

2023-01-09 15:07 UTC, andrewheard commented on FirebaseAuthExchange/Apps/ObjcSample/Podfile
>    pod 'FirebaseInstallations'
Done.

2023-01-09 15:36 UTC, ncooke3 approved these changes

2023-01-09 15:42 UTC, merged