Feature: Add animations to @FirestoreQuery
firebase/firebase-ios-sdk pull request #10813
Opened 2023-02-13 18:46 UTC by briannadoubt

### Features

- Adds a SwiftUI `Animation` parameter to the FirebaseQuery initializer.
- If animation is not `nil` then setting the data to the published value will be executed inside of a `withAnimation` block (with the given `Animation`)

### Description

1. **Use case:** Animate the data updates provided by the `@FirestoreQuery` property wrapper.
2. **Current implementation:** Unless I'm missing something, `@FirebaseQuery` doesn't animate its' published changes.
3. **Proposed solution:** Add an `Animation` parameter to the `FirestoreQueryObservable` initializer, store it in the `FirestoreQuery.Configuration`, and conditionally invoke a `withAnimation` block when setting the data.

### API Proposal

1. First, add an `Animation` object to the `FirestoreQuery.Configuration`
2. Add an optional `Animation` parameter to the `FirestoreQuery`'s initializer
3. Add a `private` method to update the `items` instance memory, with a conditional animation block (based on the configuration)
4. Update all of the setter expressions (setting the `items` value) with this new `set(items:)` func.
5. Also add conditional animation logic to the error setter to animate errors on screen.

### Firebase Product(s)

Firestore

2023-02-13 20:44 UTC, briannadoubt commented
@peterfriese - Hope you're well! ☀️ How to make the linter pass? Seems my local environment isn't setup for running it. Failing [here](https://github.com/firebase/firebase-ios-sdk/actions/runs/4166750420/jobs/7211545388).

2023-02-13 20:50 UTC, peterfriese commented
> @peterfriese - Hope you're well! ☀️ How to make the linter pass? Seems my local environment isn't setup for running it. Failing [here](https://github.com/firebase/firebase-ios-sdk/actions/runs/4166750420/jobs/7211545388).

We've got a script that can do the formatting for you. Check out the [development guide](https://github.com/firebase/firebase-ios-sdk/blob/master/CONTRIBUTING.md#style-guide), and let me know if you run into any issues (the discussions forum might also have a couple of threads that discuss setting up the local toolchain).

2023-02-14 11:42 UTC, peterfriese requested changes
Thanks for sending this PR, Brianna!

Generally looking good. I left a few comments w.r.t. adding documentation, and adding a separate view to demonstrate the difference between using the new `animated` parameter on the property wrapper instead of using the `.animated` view modifier.

I also explored a different option for performing the changes - please see [the changes on my branch](https://github.com/firebase/firebase-ios-sdk/compare/peterfriese/firestorequery-propertywrapper).

Since this is an API change, we will have to go through an API review process. This is an internal process, and might take a couple of days. I will report progress here. In the meantime, we can work on addressing my comments.

2023-03-24 20:03 UTC, briannadoubt commented
@peterfriese I've sent an update, let me know if there's anything else you'd like to see differently!

2023-06-14 11:59 UTC, peterfriese commented
Work on this continues in PR #11437.

2023-06-27 12:13 UTC, closed without merging