Long alias support for aggregations
firebase/firebase-ios-sdk pull request #11206
Opened 2023-04-28 17:13 UTC by MarkDuckworth

Long alias support for aggregations. PR to feature branch.

2023-04-30 20:54 UTC, cherylEnkidu requested changes
It looks really good! just a little bit language improvement

2023-04-30 20:54 UTC, cherylEnkidu commented on Firestore/core/src/remote/remote_objc_bridge.cc
>    }
You can use move here
```
uniqueAggregates.insert(std::move(pair));
```

2023-04-30 20:54 UTC, cherylEnkidu commented on Firestore/core/src/remote/remote_objc_bridge.cc
> +    aliasMap.insert(pair);
using move here

2023-05-05 16:25 UTC, cherylEnkidu approved these changes
thank you!

2023-05-05 16:25 UTC, cherylEnkidu commented on Firestore/core/src/remote/datastore.cc
>        // TODO(c++14): move into lambda.
can you remove the todo here?

2023-05-05 18:41 UTC, MarkDuckworth commented on Firestore/core/src/remote/datastore.cc
>        // TODO(c++14): move into lambda.
Fixed. Thank you.

2023-05-08 21:18 UTC, merged