Recaptcha Unit Tests
firebase/firebase-ios-sdk pull request #14151
Opened 2024-11-20 10:27 UTC by srushtisv

- Unit Tests for Audit Mode
- Unit Tests for MFA

2024-11-20 14:22 UTC, abub02 requested changes
Ty

2024-11-20 19:10 UTC, Xiaoshouzi-gh commented
https://github.com/firebase/firebase-ios-sdk/pull/14096 has been coped to this PR.

2024-11-20 23:29 UTC, Xiaoshouzi-gh requested changes

2024-11-21 07:06 UTC, srushtisv commented on StartMFASignInRequestTests.swift
> +// Copyright 2024 Google LLC
Yes, It should be. I added the file in Unit folder (in podfile) I'm not sure why its here. Changing it.

2024-11-21 17:35 UTC, merged