Combine Support: Sign in with the 3rd party credentials
firebase/firebase-ios-sdk pull request #7248
Opened 2021-01-05 21:50 UTC by ziadtamim

Proposal for Combine support to authenticate with Firebase using third-party credentials.

```swift 
   func sign(_ signIn: GIDSignIn!, didSignInFor user: GIDGoogleUser!, withError error: Error?) {
       // ...
       if let error = error {
         // ...
         return
       }

       guard let authentication = user.authentication else { return }
       let credential = GoogleAuthProvider.credential(withIDToken: authentication.idToken,
                                                            accessToken: authentication.accessToken)
        Auth.auth()
            .signIn(withCredential: credential)
            .mapError { $0 as NSError }
            .tryCatch(handleError)
            .sink { /* ... */ } receiveValue: {  /* ... */  }
            .store(in: &subscriptions)
    }
    
    private func handleError(_ error: NSError) throws -> AnyPublisher<AuthDataResult, Error> {
        guard isMFAEnabled && error.code == AuthErrorCode.secondFactorRequired.rawValue
        else { throw error }
        
        // The user is a multi-factor user. Second factor challenge is required.
        let resolver = error.userInfo[AuthErrorUserInfoMultiFactorResolverKey] as! MultiFactorResolver
        let displayNameString = resolver.hints.compactMap(\.displayName).joined(separator: " ")
        
        return showTextInputPrompt(withMessage: "Select factor to sign in\n\(displayNameString)")
            .compactMap { displayName in
                resolver.hints.first(where: { displayName == $0.displayName }) as? PhoneMultiFactorInfo
            }
            .flatMap { [unowned self] factorInfo in
                PhoneAuthProvider.provider()
                    .verifyPhoneNumber(withMultiFactorInfo: factorInfo, multiFactorSession: resolver.session)
                    .zip(self.showTextInputPrompt(withMessage: "Verification code for \(factorInfo.displayName ?? "")"))
                    .map { (verificationID, verificationCode) in
                        let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationID, 
                                                                                 verificationCode: verificationCode)
                        return PhoneMultiFactorGenerator.assertion(with: credential)
                    }
            }.flatMap { assertion in
                resolver.resolveSignIn(withAssertion: assertion)
            }.eraseToAnyPublisher()
    }
```

2021-01-13 16:34 UTC, peterfriese commented
HI @ziadtamim - thanks for your contribution!

I've just merged #6976 into `combine-main`, laying the groundwork for Combine support for Firebase Auth. Can you update this PR and:

1. Make sure it targets `combine-main`
2. Add some tests for your extensions. [FirebaseAuth/Tests/Unit](https://github.com/firebase/firebase-ios-sdk/tree/master/FirebaseAuth/Tests/Unit) contains tests for all the Auth providers, and you can take some inspiration for how to write the respective mocks from [FirebaseCombineSwift/Tests/Unit/Auth/EmailLinkAuthTests.swift](https://github.com/firebase/firebase-ios-sdk/blob/d90594069af8f18eeaa133d9d14ab482bd510131/FirebaseCombineSwift/Tests/Unit/Auth/EmailLinkAuthTests.swift)

2021-01-14 22:01 UTC, peterfriese commented
Ooops - looks like you'll first need to catch up to the head of combine-main before attempting the merge.

2021-01-15 08:55 UTC, ziadtamim commented
> Ooops - looks like you'll first need to catch up to the head of combine-main before attempting the merge. There is a lot of noise in your most recent change that makes it next to impossible to see the actual change you're proposing:
> 
> <img alt="Screenshot 2021-01-15 at 09 22 55" width="677" src="https://user-images.githubusercontent.com/232107/104699908-b2c23800-5713-11eb-845c-77888ab4ab4e.png">
> 
> Alternatively, create a new PR agains `combine-main`, and then abandon this one. This might actually be the easist way forward.

Thanks @peterfriese I'll fix the PR and add tests.

2021-01-17 15:46 UTC, ziadtamim commented
@peterfriese PR fixed with added tests.

2021-01-18 18:38 UTC, peterfriese requested changes
Looking good. 

Some minor naming changes in the new methods you added - see my detailed comments there.

Thanks for adding the tests! Had one minor issue there as well.

2021-01-19 09:23 UTC, peterfriese reviewed
Thanks for making those changes, @ziadtamim!

If you find some time, can you also add a short example to the README file in the root of FirebaseCombine?

2021-01-22 17:43 UTC, ziadtamim commented
@peterfriese README update ✔

2021-01-23 10:42 UTC, peterfriese requested changes
Looking good. Just some formatting issues. Once you've addressed them, we can merge this PR.

2021-01-23 10:42 UTC, peterfriese commented on FirebaseCombineSwift/README.md
> +In the `sign(_:didSignInFor:withError:)` method, get a Google ID token and Google access token from the GIDAuthentication object and exchange them for a Firebase credential. Then, Asynchronously sign
I think the official docs say it quite nicely: 

> In the `signIn:didSignInForUser:withError:` method, get a Google ID token and Google access token from the `GIDAuthentication` object and exchange them for a Firebase credential:

Let's use this and change your paragraph to:

> In the `sign(_:didSignInFor:withError:)` method, get a Google ID token and Google access token from the `GIDAuthentication` object and asynchronously exchange them for a Firebase credential:

2021-01-23 10:42 UTC, peterfriese commented on FirebaseCombineSwift/README.md
> +       let credential = GoogleAuthProvider.credential(withIDToken: authentication.idToken,
Please make sure to align the `withIDToken` and `withIDToken`. (I am painfully aware our own docs often aren't a good example ...)

2021-01-23 10:42 UTC, peterfriese commented on FirebaseCombineSwift/README.md
> +       // ...
Google indentation style is 2 spaces. Can you update the entire snippet accordingly?

2021-01-23 10:42 UTC, peterfriese commented on FirebaseCombineSwift/README.md
> +            }.flatMap { assertion in
Bring .flatMap onto the next line, just like you did in line 98.

2021-01-23 10:42 UTC, peterfriese commented on FirebaseCombineSwift/README.md
> +            }.eraseToAnyPublisher()
Same here - this way, all calls are nicely aligned.

2021-01-23 12:23 UTC, ziadtamim commented
Requested changes applied.

2021-01-23 13:06 UTC, peterfriese commented
Awesome, thanks for making those changes.

2021-01-23 13:08 UTC, merged

2021-01-23 13:09 UTC, peterfriese reviewed
LGTM!