WIP: failing merge tests
firebase/firebase-ios-sdk pull request #7276
Opened 2021-01-08 16:20 UTC by thebrianchen

2021-01-19 18:00 UTC, schmidt-sebastian requested changes
I am surprised by how pretty this looks. Thanks for doing this!

2021-01-20 17:03 UTC, thebrianchen reviewed
thanks!

2021-01-21 03:58 UTC, schmidt-sebastian approved these changes

2021-01-21 03:58 UTC, schmidt-sebastian commented on Firestore/core/src/local/local_serializer.cc
> +              transform_mutation.transform.field_transforms_count);
Do we still need this call?

2021-01-21 16:46 UTC, thebrianchen commented on Firestore/core/src/local/local_serializer.cc
> +              transform_mutation.transform.field_transforms_count);
removed.

2021-01-21 18:03 UTC, merged