[#7309] Fixed messageDisplaySuppressed Ignored on Slow Networks
firebase/firebase-ios-sdk pull request #7313
Opened 2021-01-15 18:52 UTC by yakovmanshin

[Closes #7309]

* Added an extra check on `messageDisplaySuppressed`’s value just before the message is displayed on screen
* Added the `testNoRenderingIfMessageDisplayIsSuppressedDuringImageLoading` test method that covers the scenario where `messageDisplaySuppressed` is set to `YES` after the message’s image started loading but before the message is displayed
* Added support for async image loading in `FIRIAMDisplayExecutorTests`, and a new test message `m6` whose image is loaded asynchronously; existing test messages’ behavior is left unchanged

2021-01-15 18:55 UTC, yakovmanshin commented
@googlebot I signed it!

2021-02-01 13:26 UTC, yakovmanshin commented
@christibbs Hello there! Could you have a look at this PR?

2021-02-01 23:21 UTC, christibbs commented
@yakovmanshin Sorry for the delay. The change looks good-- could you just add this log before the return on line 645 of FIRIAMDisplayExecutor.m?

```
FIRLogDebug(kFIRLoggerInAppMessaging, @"I-IAM400042",
                  @"Message display suppressed by developer at message display time.");
```

2021-02-01 23:22 UTC, christibbs commented
@yakovmanshin Make sure to run `scripts/style.sh` again to reformat!

2021-02-02 03:04 UTC, christibbs requested changes

2021-02-02 03:04 UTC, christibbs commented on FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
> +          return;
Add log here:

```
FIRLogDebug(kFIRLoggerInAppMessaging, @"I-IAM400042",
                  @"Message display suppressed by developer at message display time.");
```

2021-02-02 05:11 UTC, yakovmanshin commented on FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
> +          return;
Sure!

2021-02-02 16:29 UTC, christibbs approved these changes

2021-02-02 16:29 UTC, merged

2021-02-02 16:29 UTC, christibbs commented
@yakovmanshin Thanks for contributing to Firebase.