Add bundle cache
firebase/firebase-ios-sdk pull request #7320
Opened 2021-01-18 16:16 UTC by wu-hui

Hey there! So you want to contribute to a Firebase SDK?
Before you file this pull request, please read these guidelines:

### Discussion

  * Read the contribution guidelines (CONTRIBUTING.md).
  * If this has been discussed in an issue, make sure to link to the issue here.
    If not, go file an issue about this **before creating a pull request** to discuss.

### Testing

  * Make sure all existing tests in the repository pass after your change.
  * If you fixed a bug or added a feature, add a new test to cover your code.

### API Changes

  * At this time we cannot accept changes that affect the public API.  If you'd like to help
    us make Firebase APIs better, please propose your change in a feature request so that we
    can discuss it together.

2021-01-21 01:22 UTC, var-const requested changes

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +    : persistence_(std::move(persistence)),
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +BundleCacheTest::~BundleCacheTest() = default;
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +    ASSERT_EQ(absl::nullopt, cache_->GetBundleMetadata("bundle-1"));
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +    ASSERT_EQ(absl::nullopt, cache_->GetBundleMetadata("bundle-1"));
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.h
> + * Copyright 2019 Google
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/bundle_cache_test.h
> + * + Write a persistence factory function
Done.

2021-01-21 16:18 UTC, wu-hui commented on Firestore/core/test/unit/local/local_serializer_test.cc
Done.

2021-01-21 19:46 UTC, var-const approved these changes
LGTM (with just a couple of remaining nits).

2021-01-21 19:46 UTC, var-const commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +
Sorry, to be clear -- pretty much everything in the test file should be in an unnamed namespace. That includes any helper classes, using declarations, free functions, etc. In most cases, the unnamed namespace should start immediately after the most-nested named namespace:
```cpp
namespace firebase {
namespace firestore {
namespace local {
namespace {
```

2021-01-21 19:46 UTC, var-const commented on Firestore/core/test/unit/local/bundle_cache_test.cc
> +    : persistence_(std::move(persistence)),
Nit: please include `util/hard_assert.h`.

2021-01-21 19:46 UTC, var-const commented on Firestore/core/src/local/leveldb_bundle_cache.cc
> +    : db_(db), serializer_(serializer) {
Please include the appropriate header for `NOT_NULL` (`util/hard_assert.h`), it's best to not rely on this header being transitively included from somewhere.

2021-01-22 12:52 UTC, merged

2021-01-22 18:47 UTC, schmidt-sebastian commented on Firestore/core/src/remote/serializer.cc
> +  return Target(std::move(path), std::move(collection_group),
You should also reject Targets that have `offset` or `select` set.