Combine Support: Link user from a third-party provider
firebase/firebase-ios-sdk pull request #7504
Opened 2021-02-10 20:18 UTC by ziadtamim

Associates a user account from a third-party identity provider with this user.

```swift
Auth().currentUser
  .link(withCredential: credential)
  .sink { completion in
        // Handle completion
      } receiveValue: { authResult in
       // Handle AuthDataResult 
      }
  .store(in: &cancellables)
```

2021-02-11 00:00 UTC, paulb777 reviewed
Great to see all the tests!

2021-02-11 00:00 UTC, paulb777 commented on FirebaseCombineSwift/Sources/Auth/User+Combine.swift
> +// Copyright 2020 Google LLC
2021

2021-02-11 09:12 UTC, peterfriese requested changes
LG, just a few minor nits. Once fixed, good to be merged.

Thanks for your contribution!

2021-02-11 09:12 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +        XCTAssertEqual(Auth.auth().currentUser, user)
The original test has a few comments that explain what is being verified (see https://cs.opensource.google/firebase-sdk/firebase-ios-sdk/+/master:FirebaseAuth/Tests/Unit/FIRUserTests.m;l=1910). Let's add these here as well.

2021-02-11 20:23 UTC, ziadtamim commented
Done

2021-02-15 10:50 UTC, peterfriese approved these changes
LG, thanks!

2021-02-15 10:51 UTC, merged