Renews the user authentication
firebase/firebase-ios-sdk pull request #7534
Opened 2021-02-15 19:48 UTC by ziadtamim

Renews the user's authentication tokens by validating a fresh set of credentials supplied by the user  and returns additional identity provider data.

```swift
authResult.user
  .reauthenticate(with: googleCredential)
  .sink { completion in
    /* Handle completion */
  } receiveValue: { authResult in
    /* Handle result */
  }
  .store(in: &cancellables)
```

2021-02-16 07:47 UTC, peterfriese requested changes
LG - just a few minor nits, and some general clean-up. Once done, this can be merged.

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    let emailCredentials = ProviderCredentials(
// given

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +
// when

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    let googleCredentials = ProviderCredentials(
// given

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    let emailCredentials = ProviderCredentials(
// given

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    Auth.auth()
// when

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    let emailCredentials = ProviderCredentials(
// given

2021-02-16 07:47 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/UserTests.swift
> +    Auth.auth()
// when

2021-02-16 07:47 UTC, peterfriese commented on FirebaseDynamicLinks/Sources/Logging/FDLLogging.m
> +#else  // 32-bit
This file doesn't seem to be related to the PR, can you try to exclude it?

2021-02-16 07:47 UTC, peterfriese commented on Firestore/Example/Firestore.xcodeproj/project.pbxproj
> +		148EC47BA70CEB561D4957C1 /* bundle_spec_test.json in Resources */ = {isa = PBXBuildFile; fileRef = 24F2F48EDB1645DF4AA82EB4 /* bundle_spec_test.json */; };
Is this related to the PR? If not, let's try to remove all of these from the PR.

2021-02-16 07:47 UTC, peterfriese commented on Firestore/core/test/unit/util/ordered_code_test.cc
> +#else  // defined(NDEBUG)
This file doesn't seem to be related to the PR, can you try to exclude it?

2021-02-16 18:50 UTC, ziadtamim commented
Done

2021-02-17 09:30 UTC, peterfriese approved these changes
LGTM, thanks!

2021-02-17 09:30 UTC, merged