Combine: PhoneAuthProvider + MultiFactor Publishers
firebase/firebase-ios-sdk pull request #7734
Opened 2021-03-17 14:37 UTC by ziadtamim

2021-03-24 10:03 UTC, peterfriese requested changes
Thanks for your contributions, Ziad!

In addition to my inline comments:

1. Please ensure that the method signatures of the Combine wrappers match the ones we're wrapping (minus the completion block). There are a few methods in PhoneAuthProvider that weren't part of this PR in which we've missed this.
2. Make sure to run `./scripts/style.sh FirebaseCombineSwift` before committing
3. Please add some tests

Thanks :-)

2021-03-30 22:04 UTC, ziadtamim commented
@peterfriese Feedback applied.

2021-04-02 11:24 UTC, peterfriese requested changes
This doesn't compile - see comments below. Once compile errors are fixed, tests run green.

2021-04-02 11:24 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/PhoneAuthProviderTests.swift
> +    provider.verifyPhoneNumber(with: "", uiDelegate: nil)
Need to remove `with:` label so the test can compile.

2021-04-02 11:24 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/PhoneAuthProviderTests.swift
> +    provider.verifyPhoneNumber(with: Self.invalidPhoneNumber, uiDelegate: nil)
Need to remove `with:` label so the test can compile.

2021-04-02 11:24 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/PhoneAuthProviderTests.swift
> +    provider.verifyPhoneNumber(with: Self.phoneNumber, uiDelegate: nil)
Need to remove `with:` label so the test can compile.

2021-04-02 11:24 UTC, peterfriese commented on FirebaseCombineSwift/Tests/Unit/Auth/PhoneAuthProviderTests.swift
> +    provider.verifyPhoneNumber(with: Self.phoneNumber, uiDelegate: nil)
Need to remove `with:` label so the test can compile.

2021-04-02 11:24 UTC, peterfriese commented on FirebaseCombineSwift.podspec
> +      'Fakes/*.[mh]',
Is this correct?

2021-04-06 20:31 UTC, peterfriese approved these changes
LGTM

2021-04-06 20:33 UTC, merged