Migrate `transform:` callsites and introduce breaking version of GDT (9.0)
firebase/firebase-ios-sdk pull request #7899
Opened 2021-04-14 15:02 UTC by ncooke3

• There is an [upcoming breaking change in GDT (8.4 -> 9.0)](https://github.com/google/GoogleDataTransport/commit/0afaad7819fe7cd66d772ddebb093b89eea3b2a9) where the `transform:` API has been renamed to `transformGDTEvent:` to [avoid collisions with one of Apple's private APIs](#7177).

This PR prepares for this change by:
• Migrating callsites to the new API
• Updating specs to point to next major version of GDT (9.0)

This is planned to be a part of Firebase 8.

Fixes #7177

2021-04-14 15:07 UTC, ncooke3 commented
For this type of change, which CHANGELOGs should be modified? The FirebaseCore/CHANGELOG or the CHANGELOGs that correspond to specs that have been changed?

2021-04-14 15:39 UTC, paulb777 requested changes
Please push GDT 9.0 to SpecsDev and rerun tests

Only one overall Firebase changelog is needed in the FirebaseCore CHANGELOG

2021-04-14 21:47 UTC, paulb777 commented
To fix the CI failure, https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMLModelDownloader/Apps/Sample/Podfile should be updated to get FirebaseCoreDiagnostics from the local repo - similar syntax to https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseMLModelDownloader/Apps/Sample/Podfile#L8

2021-04-15 01:27 UTC, paulb777 approved these changes

2021-04-19 17:08 UTC, ncooke3 commented on FirebaseMLModelDownloader/Apps/Sample/Podfile
> +pod 'FirebaseCoreDiagnostics', :path => '../../../'
Fixed CI failure

2021-04-19 17:33 UTC, maksymmalyhin commented
cc @visumickey

2021-04-19 17:34 UTC, maksymmalyhin approved these changes
LGTM

2021-04-19 18:53 UTC, visumickey approved these changes
Thanks for making this change. LGTM!

2021-04-19 21:01 UTC, merged

2021-04-19 21:01 UTC, ncooke3 commented
Can address any additional feedback in a subsequent PR.