Finish FieldValue migration to Protobuf
firebase/firebase-ios-sdk pull request #8101
Opened 2021-05-18 15:48 UTC by schmidt-sebastian

This is the last PR in everyone's favorite series. It addresses random issues and all the changes that have not yet been reviewed.

2021-05-18 16:02 UTC, schmidt-sebastian commented on Firestore/core/test/unit/model/field_value_test.cc
> -TEST_F(FieldValueTest, NormalizesNaNs) {
This test only tested the test helpers since we remove the round trip through the FieldValues. It was removed.

2021-05-18 16:02 UTC, schmidt-sebastian commented on Firestore/core/test/unit/model/field_value_test.cc
> -TEST_F(FieldValueTest, CanonicalBitsAreCanonical) {
This test was moved to value_util_test

2021-05-18 23:32 UTC, var-const requested changes

2021-05-18 23:32 UTC, var-const commented on Firestore/core/src/model/server_timestamp_util.cc
> +    field->value = DeepClone(*previous_value);
It concerns me that we pass these structs around with no wrappers to clarify ownership. Definitely seems like something to address in the future.

2021-05-18 23:32 UTC, var-const commented on Firestore/core/test/unit/model/value_util_test.cc
> +  google_firestore_v1_Value long_value = Value(LONG_MAX);
Optional: you can use `std::numeric_limits<long>::max()` to avoid using a macro (here and below).

2021-05-19 22:15 UTC, schmidt-sebastian commented
Looks like ASAN party is over! Whee

2021-05-20 03:09 UTC, var-const approved these changes

2021-05-20 03:09 UTC, var-const commented on Firestore/core/src/bundle/bundle_serializer.cc
> +  for (auto it = fields.begin(); it != fields.end(); ++it) {
Ah, it looks like in this case, you only get the values in the loop, not the keys -- to get both the keys and the values, you need to call [`fields.items()`](https://github.com/nlohmann/json/blob/0972f7ff0e651f09a306dba791cc42024b8642c1/include/nlohmann/json.hpp#L4931) (kinda like in Python).

2021-05-20 03:09 UTC, var-const commented on Firestore/core/src/bundle/bundle_serializer.cc
> +  // the json iterator cannot be dereferenced.
The library defines two versions of `at` -- one taking an integer (for arrays) and one taking a key (for maps). The exception means that the overload of `at` taking an integer was called on a map. Not sure what exactly is triggering `at`, though my first suspicion would be the call to `std::distance`. If you're not interested in investigating, feel free to keep as is, but please adjust the comment to something like `A JSON map doesn't currently work with SetRepeatedField`.

2021-05-20 16:39 UTC, schmidt-sebastian commented on Firestore/core/src/bundle/bundle_serializer.cc
> +  // the json iterator cannot be dereferenced.
I updated the comment. I tried to use field.items() as well but was not able to make this work.

2021-05-20 16:39 UTC, schmidt-sebastian commented on Firestore/core/src/bundle/bundle_serializer.cc
> +  for (auto it = fields.begin(); it != fields.end(); ++it) {
Done

2021-05-20 17:57 UTC, merged