Refactoring device heuristics collection to a helper class.
firebase/firebase-ios-sdk pull request #8432
Opened 2021-07-23 19:47 UTC by eldhosembabu

Refactoring device heuristics collection to a helper class.

2021-08-03 20:05 UTC, ryanwilson approved these changes
Nit: please fix the changelog otherwise LGTM

2021-08-03 20:05 UTC, ryanwilson commented on FirebaseDynamicLinks/CHANGELOG.md
> +# v8.6.1
This will likely be 8.7.0

2021-08-03 20:24 UTC, ryanwilson requested changes
Please update the copyrights in the new files as well.

2021-08-04 22:34 UTC, eldhosembabu commented on FirebaseDynamicLinks/CHANGELOG.md
> +# v8.6.1
Changed!

2021-08-05 14:44 UTC, ryanwilson commented on FirebaseDynamicLinks/Sources/Utilities/FDLDeviceHeuristicsHelper.h
> + * Copyright 2018 Google
Please update to the latest copyright

2021-08-05 14:44 UTC, ryanwilson commented on FirebaseDynamicLinks/Sources/Utilities/FDLDeviceHeuristicsHelper.m
> + * Copyright 2018 Google
Please update to the latest copyright

2021-08-05 21:04 UTC, eldhosembabu commented on FirebaseDynamicLinks/Sources/Utilities/FDLDeviceHeuristicsHelper.h
> + * Copyright 2018 Google
Done

2021-08-05 21:04 UTC, eldhosembabu commented on FirebaseDynamicLinks/Sources/Utilities/FDLDeviceHeuristicsHelper.m
> + * Copyright 2018 Google
Done...changed to 2021

2021-08-06 20:11 UTC, ryanwilson approved these changes

2021-08-06 20:13 UTC, merged