fix: issue where deployment targets for subspec `AppCheck` in `Firebase` podspec does not match `FirebaseAppCheck` podspec
firebase/firebase-ios-sdk pull request #9187
Opened 2022-01-10 07:49 UTC by Salakar

### Discussion

The deployment targets defined in https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAppCheck.podspec#L20-L23 are not reflected in the [`AppCheck` subspec](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase.podspec#L102-L104) in the main `Firebase` podspec. This PR updates them to match.

### Testing

  * N/A

### API Changes

  * N/A

2022-01-10 15:35 UTC, paulb777 requested changes
@Salakar Thanks for pointing this out. The fix is actually the obvious to update FirebaseAppCheck.podspec to match since AppCheck requires iOS 11 etc.  Let us know if you want to continue. Otherwise, we'll make the correction before the next release.

2022-01-10 17:41 UTC, paulb777 commented
Hmm, on further investigation, I'm not sure the correct setup here. https://firebase.google.com/docs/ios/learn-more#firebase_library_support_by_platform shows three different lines for AppCheck.

2022-01-10 17:50 UTC, paulb777 approved these changes
Based on the updates in #8388, this change should have been done then as well, so it looks good. Thanks!  and thanks to @ryanwilson for tracking down the provenance.

2022-01-10 17:51 UTC, merged

2022-01-18 17:56 UTC, Semty commented
@paulb777 hey! it seems that the desired effect is seen only with using Cocoapods, but with SPM I get this after adding AppCheck for watchOS target:
```DeviceCheck is not available when building for watchOS.```