Add FIREBASE_LD_EXECUTABLE cmake cache variable
firebase/firebase-ios-sdk pull request #9932
Opened 2022-06-21 16:45 UTC by dconeybe

The cmake build scripts gain a new cache variable, `FIREBASE_LD_EXECUTABLE`, which, if specified, instructs the C/C++ linking steps to use the specified linker executable instead of the default linker executable (which is `ld` for clang and gcc).

The motivating use case for using a custom linker is to enable using `mold` (https://github.com/rui314/mold), a custom linker that is compatible with, but significantly faster than, the default `ld` linker. For continuous builds and continuous tests, this doesn't really matter and this new cache variable is not intended to be used in this case; however, during build/test cycles the linking time is one of the biggest contributors to the length of such cycles. Reducing the linking time makes local development easier and less distracting.

Personally, using `mold` on my linux box reduced link times for `firestore_remote_test` from 7.70s down to 1.54s, a 5x speed improvement.

To use `mold`, first install it (e.g. via `brew install mold`) and then specify `-DFIREBASE_LD_FILENAME:STRING=mold` to cmake. Voila, you get faster builds!

#no-changelog

2022-06-24 21:34 UTC, ehsannas requested changes

2022-06-24 21:34 UTC, ehsannas commented on CMakeLists.txt
> +  FIREBASE_LD_FILENAME
`FIREBASE_LD_EXECUTABLE`?

2022-06-26 01:30 UTC, dconeybe commented on CMakeLists.txt
> +  FIREBASE_LD_FILENAME
Nice catch!

2022-06-27 13:54 UTC, ehsannas approved these changes

2022-06-27 18:34 UTC, merged